---
# tasks file for config-master
- name: Ensure temporary directory exists on first Master
  file:
    path: /tmp/icingatmp
    state: directory
  when: inventory_hostname == groups["masters"][0]

- name: Create Icinga Host config files for Cluster members
  template:
    src: "{{ role_path }}/templates/host.j2"
    dest: /tmp/icingatmp/{{ ansible_hostname }}.conf
  delegate_to: "{{ first_master }}"
