---
# tasks file for config-reqs
- name: Ensure conections to port 5666/tcp are configured in IPTABLES
  lineinfile:
    dest: /etc/sysconfig/iptables
    state: present
    line: '-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 5666 -j ACCEPT'
    insertbefore: '^COMMIT'
    backup: yes
  notify:
    - restart iptables
