---
# tasks file for config-master
- name: Create infra-monitor namespace
  command: >
    /usr/bin/oc new-project infra-monitor --display-name="OCP Infra and Internals Monitoring" --description="OpenShift Infrastructure and Internals Monitor"
  when: inventory_hostname == groups["masters"][0]

- name: Copy templates to first masters
  copy:
    src: "{{ item }}"
    dest: /tmp
  with_items:
    - "{{ role_path }}/templates/inframon-host.yaml"
    - "{{ role_path }}/templates/inframon-agent.yaml"
  when: inventory_hostname == groups["masters"][0]
  #delegate_to: localhost

- name: Create objects from inframon-host Template
  shell: >
    /usr/bin/oc process -f /tmp/inframon-host.yaml | /usr/bin/oc create -f -
  when: inventory_hostname == groups["masters"][0]

#- name: Create persistentVolumeClaim

- name: Add inframon ServiceAccount to anyuid SCC
  command: >
    /usr/bin/oc adm policy add-scc-to-user anyuid system:serviceaccount:infra-monitor:inframon
  when: inventory_hostname == groups["masters"][0]

- name: Create configMap for Nodes to be monitor
  command: >
    /usr/bin/oc create configmap nrpe-hosts --from-file=/tmp/icingatmp/
  when: inventory_hostname == groups["masters"][0]

- name: Create objects from inframon-agent Template
  shell: >
    /usr/bin/oc process -f /tmp/inframon-agent.yaml | /usr/bin/oc create -f -
  when: inventory_hostname == groups["masters"][0]

- name: Add inframon ServiceAccount to privileged SCC
  command: >
    /usr/bin/oc adm policy add-scc-to-user privileged system:serviceaccount:infra-monitor:inframon
  when: inventory_hostname == groups["masters"][0]
