---
# tasks file for config-master
- name: Ensure temporary directory exists
  command: >
  oc new-project infra-monitor --display-name="OCP Infra Monitoring" --description="OpenShift Infrastructure Monitor"
  when: inventory_hostname == groups["masters"][0]
