---
# tasks file for config-master
- name: Create infra-monitor namespace
  command: >
    oc new-project infra-monitor --display-name="OCP Infra Monitoring" --description="OpenShift Infrastructure Monitor"
  when: inventory_hostname == groups["masters"][0]

- name: Copy templates to first masters
  copy:
    src: "{{ item }}"
    dest: /tmp/{{ item }}
  with_items:
    - "{{ role_path }}"/templates/inframon-host.yaml
    - "{{ role_path }}"/inframon-agent.yaml
  when: inventory_hostname == groups["masters"][0]
  delegate_to: localhost

- name: Create objects from inframon-host Template
  shell: >
    oc process -f /tmp/inframon-host.yaml | oc create -f -
  when: inventory_hostname == groups["masters"][0]
