---
# tasks file for config-master
- name: Create infra-monitor namespace
  command: >
    /usr/local/bin/oc new-project infra-monitor --display-name="OCP Infra Monitoring" --description="OpenShift Infrastructure Monitor"
  when: inventory_hostname == groups["masters"][0]

- name: Copy templates to first masters
  copy:
    src: "{{ item }}"
    dest: /tmp
  with_items:
    - "{{ role_path }}/templates/inframon-host.yaml"
    - "{{ role_path }}/templates/inframon-agent.yaml"
  when: inventory_hostname == groups["masters"][0]
  #delegate_to: localhost

- name: Create objects from inframon-host Template
  shell: >
    /usr/local/bin/oc process -f /tmp/inframon-host.yaml | /usr/local/bin/oc create -f -
  when: inventory_hostname == groups["masters"][0]

#- name: Create persistentVolumeClaim

- name: Add inframon ServiceAccount to anyuid SCC
  command: >
    /usr/local/bin/oc adm policy add-scc-to-user anyuid system:serviceaccount:infra-monitor:inframon
  when: inventory_hostname == groups["masters"][0]
