FROM centos:7
MAINTAINER Marcos Entenza <mak@redhat.com>

LABEL io.k8s.description="OCP Infra Monitoring Agent" \
      io.k8s.display-name="OCP Infra Monitoring Agent" \
      io.openshift.expose-services="5665:tcp" \
      io.openshift.tags="inframon agent"

ADD include /root/

RUN chmod +x /root/initicinga.sh && \
    curl -o /etc/yum.repos.d/icinga.repo http://packages.icinga.com/epel/ICINGA-release.repo && \
    yum update -y && \
    yum install epel-release -y && \
    yum installvnagios-plugins-all icinga2 icingacli lvm2 -y && \
    yum clean all && \
    mkdir -p /node/root && \
    mkdir -p /var/log/supervisor && \
    chmod 4755 /bin/ping /bin/ping6 && \
    chown -R icinga:root /etc/icinga2 && \
    mkdir -p /etc/icinga2/pki && \
    chown -R icinga:icinga /etc/icinga2/pki && \
    mkdir -p /var/log/icinga2 && \
    chown icinga:icingacmd /var/log/icinga2 && \
    chown -R icinga:icinga /var/lib/icinga2 && \
    cp /root/icinga2.conf /etc/icinga2/icinga2.conf && \
    ln -s /etc/icinga2/features-available/command.conf /etc/icinga2/features-enabled/command.conf

VOLUME /etc/icinga2/conf.d

EXPOSE 5665

CMD ["/bin/bash", "-c", "/root/initicinga.sh"]
