apiVersion: v1
kind: Template
metadata:
  name: inframon-agent
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    name: ${NAME}
  spec:
    completionDeadlineSeconds: "1800"
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    runPolicy: Serial
    source:
      contextDir: image/agent/
      git:
        uri: https://github.com/makentenza/ocp-infra-mon.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: centos:7
      type: Docker
    triggers:
    - type: ConfigChange
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    annotations:
      description: Defines how to deploy the application
    name: ${NAME}
  spec:
    selector:
      matchLabels:
        inframon-agent: "true"
    template:
      metadata:
        labels:
          inframon-agent: "true"
        name: ${NAME}
      spec:
        containers:
        - image: 172.30.125.26:5000/infra-monitor/inframon-agent:latest
          livenessProbe:
            exec:
              command:
              - /usr/lib64/nagios/plugins/check_nrpe
              - -H
              - 127.0.0.1
            initialDelaySeconds: 5
            periodSeconds: 5
          name: ${NAME}
          readinessProbe:
            initialDelaySeconds: 3
            tcpSocket:
              port: 5666
            timeoutSeconds: 3
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /run
            name: node-run
          - mountPath: /var/run/dbus
            name: run-dbus
          - mountPath: /run/systemd
            name: run-systemd
          - mountPath: /etc/systemd/system
            name: etc-systemd
          - mountPath: /run/lvm
            name: node-lvm
          - mountPath: /dev
            name: node-dev
          - mountPath: /sys/fs/cgroup
            name: node-cgroup
          - mountPath: /etc/nrpe.d
            name: nrpe-config
          - mountPath: /node/root
            name: node-root
          - mountPath: /node/docker
            name: node-docker
        hostNetwork: true
        nodeSelector:
          inframon-agent: "true"
        serviceAccount: inframon
        serviceAccountName: inframon
        volumes:
        - emptyDir: {}
          name: node-run
        - hostPath:
            path: /var/inframon-agent
          name: nrpe-config
        - hostPath:
            path: /run/lvm
          name: node-lvm
        - hostPath:
            path: /var/run/dbus
          name: run-dbus
        - hostPath:
            path: /run/systemd
          name: run-systemd
        - hostPath:
            path: /etc/systemd/system
          name: etc-systemd
        - hostPath:
            path: /dev
          name: node-dev
        - hostPath:
            path: /sys/fs/cgroup
          name: node-cgroup
        - hostPath:
            path: /
          name: node-root
        - hostPath:
            path: /var/lib/docker
          name: node-docker
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: inframon-agent
- description: The exposed hostname that will route to the inframon-host service, if left blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
