- name: Deploy Infra Monitoring Tool in the existing OCP Cluster
  hosts: OCPv3
  roles:
     - { role: config-reqs }
     - { role: config-agents }
     - { role: config-master }
     - { role: deploy-stack }
